//! Public wire contracts. Provider identity and board truth never belong here.
pub use liar_core::rules::{GameRules, RulesSnapshot};
use serde::Serialize;
use ts_rs::TS;

#[derive(Debug, Serialize, TS)]
pub struct PublicAccount {
    pub id: String,
    pub nickname: String,
}

#[derive(Debug, Serialize, TS)]
#[serde(rename_all = "snake_case")]
pub enum ServiceStatus {
    Ok,
    Unavailable,
}

#[derive(Debug, Serialize, TS)]
pub struct HealthResponse {
    pub status: ServiceStatus,
}

pub fn public_types() -> String {
    let config = ts_rs::Config::default();
    format!(
        "// Generated by liar-protocol; do not edit.\nexport {}\nexport {}\nexport {}\nexport {}\nexport {}\n",
        PublicAccount::decl(&config),
        ServiceStatus::decl(&config),
        HealthResponse::decl(&config),
        GameRules::decl(&config),
        RulesSnapshot::decl(&config)
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn account_projection_contains_only_public_game_identity() {
        let account = PublicAccount {
            id: "account-id".into(),
            nickname: "Player 7".into(),
        };
        assert_eq!(
            serde_json::to_value(account).unwrap(),
            serde_json::json!({
                "id": "account-id", "nickname": "Player 7"
            })
        );
    }
}
