//! Public wire contracts. Provider identity and board truth never belong here.
pub mod auth;
pub mod daily;
pub mod game;
pub mod lobby;
pub mod online;
pub mod results;
pub mod tutorial;
pub use liar_core::rules::{BotProfiles, BotSettings, GameRules, RulesSnapshot};
use serde::Serialize;
use ts_rs::TS;

#[derive(Debug, Serialize, TS)]
pub struct PublicAccount {
    pub id: String,
    pub nickname: String,
}

#[derive(Debug, Serialize, TS)]
#[serde(rename_all = "snake_case")]
pub enum ServiceStatus {
    Ok,
    Unavailable,
}

#[derive(Debug, Serialize, TS)]
pub struct HealthResponse {
    pub status: ServiceStatus,
}

pub fn public_types() -> String {
    let config = ts_rs::Config::default();
    let mut declarations = vec![
        PublicAccount::decl(&config),
        ServiceStatus::decl(&config),
        HealthResponse::decl(&config),
        GameRules::decl(&config),
        RulesSnapshot::decl(&config),
        BotSettings::decl(&config),
        BotProfiles::decl(&config),
    ];
    declarations.extend(game::declarations(&config));
    declarations.extend(online::declarations(&config));
    declarations.extend(lobby::declarations(&config));
    declarations.extend(results::declarations(&config));
    declarations.extend(tutorial::declarations(&config));
    declarations.extend(daily::declarations(&config));
    declarations.extend(auth::declarations(&config));
    format!(
        "// Generated by liar-protocol; do not edit.\nexport const DAILY_SEED_VERSION = {};\nexport const PROTOCOL_VERSION = {};\nexport const MAX_INPUT_BYTES = {};\nexport const MAX_OUTPUT_BYTES = {};\nexport {}\nexport const DEFAULT_RULES: RulesSnapshot = {};\n",
        liar_core::daily::DAILY_SEED_VERSION,
        game::PROTOCOL_VERSION,
        game::MAX_INPUT_BYTES,
        game::MAX_OUTPUT_BYTES,
        declarations.join("\nexport "),
        serde_json::to_string(&RulesSnapshot::bundled()).expect("Public rules serialize")
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn account_projection_contains_only_public_game_identity() {
        let account = PublicAccount {
            id: "account-id".into(),
            nickname: "Player 7".into(),
        };
        assert_eq!(
            serde_json::to_value(account).unwrap(),
            serde_json::json!({
                "id": "account-id", "nickname": "Player 7"
            })
        );
    }
}
