// Generated by liar-protocol; do not edit.
export type PublicAccount = { id: string, nickname: string, };
export type ServiceStatus = "ok" | "unavailable";
export type HealthResponse = { status: ServiceStatus, };
